<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rigel" nsURI="urn:org.nasdanika.rigel" nsPrefix="org.nasdanika.rigel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="A model of value stream where something (value) is created via a series of activities performed by participants using inputs and resources (e.g. tools) and producing outputs. &#xA;Activities are owned by engineers who identify activity improvement opportunities as issues and resolve them to make the value stream more efficient. &#xA;&#xA;For example, a development activity would have requirements as input, source code as output and IDE as a resource. &#xA;The activity engineer may identify an improvement opportunity &quot;Create a code generator&quot;, which would reduce duration of the activity.&#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PackageElement" abstract="true" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Model element which can be contained by a package."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPackage" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract container of package elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PackageElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container elements."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Элементы пакета"/>
        <details key="documentation_ru" value="Элементы пакета"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//PackageElement ../../org.nasdanika.engineering/model/engineering.ecore#//EngineeredElement #//IPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container of package elements. Packages are used to organize model elements into a hierarchy."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//Flow" eOpposite="#//Flow/paricipants">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activities in which this actor participates."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Действия"/>
        <details key="documentation_ru" value="Действия в которых участвует исполнитель"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//PackageElement ../../org.nasdanika.engineering/model/engineering.ecore#//EngineeredElement #//Participant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Actors perform activities using resources consuming and producing artifacts."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true" eSuperTypes="#//PackageElement ../../org.nasdanika.engineering/model/engineering.ecore#//EngineeredElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Flow is an abstract container of flow elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FlowElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Flows are composed from flow elements."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paricipants" upperBound="-1"
        eType="#//Participant" eOpposite="#//Participant/flows">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="One or more actors participate in completion of a flow."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Участники"/>
        <details key="documentation_ru" value="Один или более исполнителей, участвующих в выполнении работы."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sum of total sizes of this flow children plus the size of self if instance of activity."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalProgress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Calculated total flow progress in percent. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Element of a (composite) activity."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true" eSuperTypes="#//FlowElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Source of transitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundTransitions" upperBound="-1"
        eType="#//Transition" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Outbound transitions."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Исходящие"/>
        <details key="documentation_ru" value="Исходящие (что?) Точки выхода?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/producers">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts output/produced by this source."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Артефакт"/>
        <details key="documentation_ru" value="Артефакты производимые этим источником"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//PackageElement #//Source">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Start pseudo-activity."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" abstract="true" eSuperTypes="#//FlowElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Target of transitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inboundTransitions" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Inbound transitions."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Вход в работу/операцию"/>
        <details key="documentation_ru" value="???Inbound transitions."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Artifact" eOpposite="#//Artifact/consumers">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Input artifacts consumed by this target."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Входящие артефакты"/>
        <details key="documentation_ru" value="Входящие артефакты необходимые для выполнения целевого этапа работы"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//PackageElement #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="End pseudo-activity."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partition" eSuperTypes="#//Flow #//FlowElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Partition is a grouping of flow elements associating participants and resources with the contained elements. "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//Flow #//Source #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="By performing an activity participants produce outputs from inputs using resources."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activity size in some unit used by all activities. For example - hours, points, dollars."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activity progress in percent. Value between 0 and 100. Progress can be used in &quot;instance&quot; models which are used to model and track execution of an actual effort as opposed to &quot;template&quot; models which explain steps to complete an effort."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Milestone" eSuperTypes="#//PackageElement #//Source #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A milestone shows an important achievement in a flow. &#xA;The milestones represent a sequence of events that incrementally build up until flow completion."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sum of size of all activities which need to be completed to reach this milestone from the start of the previous milestone(s)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Calculated total progress toward achiveing the milestone in percent. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="missed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if target date is set, the current date is after the target date and progress is less than 100%"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityReference" eSuperTypes="#//PackageElement #//Source #//Target">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="References a shared activity defined elsewhere."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="By performing an activity participants produce outputs from inputs using resources."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Работа"/>
        <details key="documentation_ru" value="Выполняя работу исполнители производят исходящие (целевые) артефакты, используя входящие артефакты и ресурсы."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//PackageElement ../../org.nasdanika.engineering/model/engineering.ecore#//EngineeredElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Artifact is something output/produced by a source and consumed by a target as input. For example - source code, user guide, binary code. Artifacts are passed between activities over transitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumers" upperBound="-1"
        eType="#//Target" eOpposite="#//Target/inputs">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Targets consuming this artifact as their input."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Потребители"/>
        <details key="documentation_ru" value="Работы или операции для которых данный аритефакт является входящим."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producers" upperBound="-1"
        eType="#//Source" eOpposite="#//Source/outputs">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sources emitting this artifact as their output."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Производители"/>
        <details key="documentation_ru" value="Работа или операция результатом которой является данный артефакт"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Artifact" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts can be nested. E.g. a zip archive contains directories which contain files."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Вложенные артефакты"/>
        <details key="documentation_ru" value="Артефакты могут быть вложенными друг в друга. Например: zip, содержащий папки, содержащие файлы."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//PackageElement ../../org.nasdanika.engineering/model/engineering.ecore#//EngineeredElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Something leveraged by an actor to perform an activity. For example - a tool."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Resource" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resource can be nested. E.g. a virtual machine may host a web server."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Вложенные ресурсы"/>
        <details key="documentation_ru" value="Ресурсы могут быть вложенными, многокомпонентными. Например, виртуальная машина может включать в себя веб-сервер."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources may host artifacts."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Артефакт"/>
        <details key="documentation_ru" value="Ресурсы могут включать в себя артефакты"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transition from its containing source element to a target element. May pass artifacts in both directions. E.g. a transition to &quot;Commit code&quot; may take &quot;Source code&quot; as input and return &quot;Commit ID&quot; as a result."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" eOpposite="#//Target/inboundTransitions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Transition target."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Целевой элемент"/>
        <details key="documentation_ru" value="Работа/операция, являющаяся целью передачи артефакта, выполнение которой невозможно до выполнения работы-источника артефакта."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Artifact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts passed by the source to the transition and delivered to the target."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Входящие артефакты"/>
        <details key="documentation_ru" value="Артефакты предаваемые от элемента-источника к целевому элементу через переход."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//Artifact">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Artifacts returned by the target to be delivered to the source."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Результат передачи"/>
        <details key="documentation_ru" value="Артефакты возвращаемые целевым элементом элементу источнику."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A generic relationship between model elements."/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="label_ru" value="Ассоциация"/>
      <details key="documentation_ru" value="Отношения наследования между элементами модели"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//PackageElement">
      <eAnnotations source="urn:org.nasdanika">
        <details key="label_ru" value="Цель"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
